version: '3.7'
services:
  application1:
    image: application1:latest
    build: ./application1 
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  application2:
    image: application2:latest      
    build: ./application2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp